// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iprqyjogagghpuvidyfx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlwcnF5am9nYWdnaHB1dmlkeWZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNTg2MjIsImV4cCI6MjA2MzkzNDYyMn0.juDhMN_3sLSu4O51yl6MxMuPNvZN0t4LWXeqHV-eElo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);